### PR TITLE
Generic Key Type

### PR DESCRIPTION
**Pull request by grinka**
Added the generic key type - IComparable instead of strict double

### CODE REVIEW

**Comment by sqeezy** [comment]
First of all - Thanks for partaking in this small project. Never would have guessed that someone is interested.
I think it would be better to use the type name FibonacciHeap for the generic baseclass. The implementation for double keys then would be a FibonacciHeapOfDouble or something similar.
If you could adjust that and send me antother PR, that would be great.

**Comment by grinka** [comment]
I would also love to add some tests to analyze results

**Comment by sqeezy** [comment]
Feel free to do so. Are interested in this kind of structures in general or just this special sorting technique?

**Comment by grinka** [comment]
Are you going to accept the pull request or maybe give me rights to update non-master branch?
BTW: I am interested in working with different data structure, sorting and searching algorithms, So if you'd like to do it together - it would be nice. 
I am going to create samples for most known sorting algorithms, different kinds of heaps, binary balanced and non-balanced trees.

**Comment by sqeezy** [comment]
As is said I would like those mentioned changes in naming of the classes. Let's work this PR out and if you want we can talk about rights to commit or a shared repo later.

**Comment by grinka** [comment]
I renamed the classes and created a pull request. Isn't it? :)

**Comment by sqeezy** [comment]
Oh my bad there. I'm not used to merging PMs honestly. Nice to finally test this out. How should we contact? What's your favorite way to chat/interact?

**Comment by grinka** [comment]
Skype, Telegram, Whatsap, Slack, Email - what do you prefer?

**Comment by sqeezy** [comment]
I think we can start with email. My address is public on Github, so you can
just text me. I'm somewhat busy at weekdays but if there is an interesting
project to do, I will surely find some time for trees,heaps and lists.

**Pull request merged**
